spring.application.name=studyPlanner

spring.datasource.url=jdbc:postgresql://localhost:5432/studyplanner
spring.datasource.username=postgres
spring.datasource.password=Turemus1!

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true